# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headLine = QtWidgets.QLabel(self.centralwidget)
        self.headLine.setGeometry(QtCore.QRect(290, 30, 171, 41))
        self.headLine.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.headLine.setObjectName("headLine")
        self.insert_info = QtWidgets.QLabel(self.centralwidget)
        self.insert_info.setGeometry(QtCore.QRect(90, 120, 54, 12))
        self.insert_info.setObjectName("insert_info")
        self.inquiry_info = QtWidgets.QLabel(self.centralwidget)
        self.inquiry_info.setGeometry(QtCore.QRect(90, 280, 54, 12))
        self.inquiry_info.setObjectName("inquiry_info")
        self.handle_info = QtWidgets.QLabel(self.centralwidget)
        self.handle_info.setGeometry(QtCore.QRect(90, 380, 54, 12))
        self.handle_info.setObjectName("handle_info")
        self.instock_btn = QtWidgets.QPushButton(self.centralwidget)
        self.instock_btn.setGeometry(QtCore.QRect(90, 150, 101, 51))
        self.instock_btn.setObjectName("instock_btn")
        self.catalog_btn = QtWidgets.QPushButton(self.centralwidget)
        self.catalog_btn.setGeometry(QtCore.QRect(200, 150, 101, 51))
        self.catalog_btn.setObjectName("catalog_btn")
        self.content_btn = QtWidgets.QPushButton(self.centralwidget)
        self.content_btn.setGeometry(QtCore.QRect(310, 150, 101, 51))
        self.content_btn.setObjectName("content_btn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(90, 130, 161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.borrow_btn = QtWidgets.QPushButton(self.centralwidget)
        self.borrow_btn.setGeometry(QtCore.QRect(90, 210, 101, 51))
        self.borrow_btn.setObjectName("borrow_btn")
        self.whereabouts_btn = QtWidgets.QPushButton(self.centralwidget)
        self.whereabouts_btn.setGeometry(QtCore.QRect(90, 310, 101, 51))
        self.whereabouts_btn.setObjectName("whereabouts_btn")
        self.subscribe_btn = QtWidgets.QPushButton(self.centralwidget)
        self.subscribe_btn.setGeometry(QtCore.QRect(90, 410, 101, 51))
        self.subscribe_btn.setObjectName("subscribe_btn")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(90, 290, 161, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(90, 390, 161, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(480, 90, 179, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.info = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.info.setContentsMargins(0, 0, 0, 0)
        self.info.setObjectName("info")
        self.mode_info = QtWidgets.QLabel(self.layoutWidget)
        self.mode_info.setObjectName("mode_info")
        self.info.addWidget(self.mode_info)
        self.logout = QtWidgets.QPushButton(self.layoutWidget)
        self.logout.setObjectName("logout")
        self.info.addWidget(self.logout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.logout.clicked.connect(MainWindow.log_out)
        self.instock_btn.clicked.connect(MainWindow.instock_register)
        self.catalog_btn.clicked.connect(MainWindow.catalog_register)
        self.content_btn.clicked.connect(MainWindow.content_register)
        self.borrow_btn.clicked.connect(MainWindow.borrow_register)
        self.whereabouts_btn.clicked.connect(MainWindow.journal_whereabouts_inquiry)
        self.subscribe_btn.clicked.connect(MainWindow.subscribe)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headLine.setText(_translate("MainWindow", "期刊管理系统"))
        self.insert_info.setText(_translate("MainWindow", "信息录入"))
        self.inquiry_info.setText(_translate("MainWindow", "信息查询"))
        self.handle_info.setText(_translate("MainWindow", "信息处理"))
        self.instock_btn.setText(_translate("MainWindow", "期刊入库登记"))
        self.catalog_btn.setText(_translate("MainWindow", "期刊目录登记"))
        self.content_btn.setText(_translate("MainWindow", "期刊内容登记"))
        self.borrow_btn.setText(_translate("MainWindow", "借阅登记"))
        self.whereabouts_btn.setText(_translate("MainWindow", "期刊去向查询"))
        self.subscribe_btn.setText(_translate("MainWindow", "期刊征订"))
        self.mode_info.setText(_translate("MainWindow", "当前模式：管理员"))
        self.logout.setText(_translate("MainWindow", "退出"))
