# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_and_inquiry.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.return_btn = QtWidgets.QPushButton(self.centralwidget)
        self.return_btn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.return_btn.setObjectName("return_btn")
        self.headLine = QtWidgets.QLabel(self.centralwidget)
        self.headLine.setGeometry(QtCore.QRect(300, 20, 171, 41))
        self.headLine.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.headLine.setObjectName("headLine")
        self.booked_journal = QtWidgets.QTableWidget(self.centralwidget)
        self.booked_journal.setGeometry(QtCore.QRect(60, 190, 601, 271))
        self.booked_journal.setObjectName("booked_journal")
        self.booked_journal.setColumnCount(5)
        self.booked_journal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.booked_journal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booked_journal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booked_journal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booked_journal.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booked_journal.setHorizontalHeaderItem(4, item)
        self.book_btn = QtWidgets.QPushButton(self.centralwidget)
        self.book_btn.setGeometry(QtCore.QRect(300, 130, 111, 23))
        self.book_btn.setObjectName("book_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 71, 16))
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(110, 90, 511, 20))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.journal_name = QtWidgets.QLineEdit(self.splitter)
        self.journal_name.setObjectName("journal_name")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.year = QtWidgets.QSpinBox(self.splitter)
        self.year.setMinimum(1949)
        self.year.setMaximum(2020)
        self.year.setProperty("value", 2020)
        self.year.setObjectName("year")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setObjectName("label_3")
        self.volume = QtWidgets.QSpinBox(self.splitter)
        self.volume.setMinimum(1)
        self.volume.setObjectName("volume")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.issue = QtWidgets.QSpinBox(self.splitter)
        self.issue.setMinimum(1)
        self.issue.setObjectName("issue")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.return_btn.clicked.connect(MainWindow.Return)
        self.book_btn.clicked.connect(MainWindow.Book)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.return_btn.setText(_translate("MainWindow", "返回"))
        self.headLine.setText(_translate("MainWindow", "我的预定"))
        item = self.booked_journal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期刊名称"))
        item = self.booked_journal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "年"))
        item = self.booked_journal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "卷"))
        item = self.booked_journal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "期"))
        item = self.booked_journal.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "预定时间"))
        self.book_btn.setText(_translate("MainWindow", "预定"))
        self.label_5.setText(_translate("MainWindow", "已预定期刊"))
        self.label.setText(_translate("MainWindow", "期刊名称"))
        self.label_2.setText(_translate("MainWindow", "年"))
        self.label_3.setText(_translate("MainWindow", "卷"))
        self.label_4.setText(_translate("MainWindow", "期"))
