# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'content_registration.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.return_btn = QtWidgets.QPushButton(self.centralwidget)
        self.return_btn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.return_btn.setObjectName("return_btn")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(80, 410, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.headLine = QtWidgets.QLabel(self.centralwidget)
        self.headLine.setGeometry(QtCore.QRect(280, 30, 171, 41))
        self.headLine.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.headLine.setObjectName("headLine")
        self.new_content = QtWidgets.QTableWidget(self.centralwidget)
        self.new_content.setGeometry(QtCore.QRect(70, 100, 601, 301))
        self.new_content.setRowCount(15)
        self.new_content.setObjectName("new_content")
        self.new_content.setColumnCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_content.setHorizontalHeaderItem(11, item)
        self.operation_set = QtWidgets.QSplitter(self.centralwidget)
        self.operation_set.setGeometry(QtCore.QRect(230, 410, 281, 23))
        self.operation_set.setOrientation(QtCore.Qt.Horizontal)
        self.operation_set.setHandleWidth(60)
        self.operation_set.setObjectName("operation_set")
        self.submit_btn = QtWidgets.QPushButton(self.operation_set)
        self.submit_btn.setObjectName("submit_btn")
        self.clear_btn = QtWidgets.QPushButton(self.operation_set)
        self.clear_btn.setObjectName("clear_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.clear_btn.clicked.connect(self.new_content.clearContents)
        self.return_btn.clicked.connect(MainWindow.Return)
        self.add_btn.clicked.connect(MainWindow.AddLine)
        self.submit_btn.clicked.connect(MainWindow.Submit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.return_btn.setText(_translate("MainWindow", "返回"))
        self.add_btn.setText(_translate("MainWindow", "添加"))
        self.headLine.setText(_translate("MainWindow", "期刊内容登记"))
        item = self.new_content.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期刊名称"))
        item = self.new_content.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "年"))
        item = self.new_content.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "卷"))
        item = self.new_content.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "期"))
        item = self.new_content.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "论文题目"))
        item = self.new_content.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "论文作者"))
        item = self.new_content.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "关键字1"))
        item = self.new_content.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "关键字2"))
        item = self.new_content.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "关键字3"))
        item = self.new_content.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "关键字4"))
        item = self.new_content.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "关键字5"))
        item = self.new_content.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "页码"))
        self.submit_btn.setText(_translate("MainWindow", "提交"))
        self.clear_btn.setText(_translate("MainWindow", "清空"))
