# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subscription.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headLine = QtWidgets.QLabel(self.centralwidget)
        self.headLine.setGeometry(QtCore.QRect(300, 10, 171, 41))
        self.headLine.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.headLine.setObjectName("headLine")
        self.return_btn = QtWidgets.QPushButton(self.centralwidget)
        self.return_btn.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.return_btn.setObjectName("return_btn")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 90, 591, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.old_journal = QtWidgets.QWidget()
        self.old_journal.setObjectName("old_journal")
        self.old_select = QtWidgets.QTableWidget(self.old_journal)
        self.old_select.setGeometry(QtCore.QRect(40, 20, 451, 261))
        self.old_select.setObjectName("old_select")
        self.old_select.setColumnCount(4)
        self.old_select.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.old_select.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.old_select.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.old_select.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.old_select.setHorizontalHeaderItem(3, item)
        self.tabWidget.addTab(self.old_journal, "")
        self.new_journal = QtWidgets.QWidget()
        self.new_journal.setObjectName("new_journal")
        self.new_select = QtWidgets.QTableWidget(self.new_journal)
        self.new_select.setGeometry(QtCore.QRect(40, 20, 451, 231))
        self.new_select.setRowCount(20)
        self.new_select.setObjectName("new_select")
        self.new_select.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.new_select.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_select.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_select.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.new_select.setHorizontalHeaderItem(3, item)
        self.clear_btn = QtWidgets.QPushButton(self.new_journal)
        self.clear_btn.setGeometry(QtCore.QRect(210, 260, 91, 23))
        self.clear_btn.setObjectName("clear_btn")
        self.tabWidget.addTab(self.new_journal, "")
        self.generate_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generate_btn.setGeometry(QtCore.QRect(280, 440, 141, 23))
        self.generate_btn.setObjectName("generate_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.return_btn.clicked.connect(MainWindow.Return)
        self.clear_btn.clicked.connect(self.new_select.clearContents)
        self.generate_btn.clicked.connect(MainWindow.Submit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headLine.setText(_translate("MainWindow", "期刊征订"))
        self.return_btn.setText(_translate("MainWindow", "返回"))
        item = self.old_select.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期刊名"))
        item = self.old_select.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISSN号"))
        item = self.old_select.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "是否续订"))
        item = self.old_select.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "征订数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.old_journal), _translate("MainWindow", "往年期刊征订"))
        item = self.new_select.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "期刊名"))
        item = self.new_select.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ISSN号"))
        item = self.new_select.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "邮发代号"))
        item = self.new_select.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "征订数量"))
        self.clear_btn.setText(_translate("MainWindow", "清空"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.new_journal), _translate("MainWindow", "新增期刊征订"))
        self.generate_btn.setText(_translate("MainWindow", "生成征订表"))
